import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import PageTranstation from "@/components/PageTranstation";
import StairTranstion from "@/components/StairTranstion";

const jetBrainsMono = JetBrains_Mono({
  subsets: ["latin"], // Specify the subset(s) you need
  weight: ["400", "500", "600", "700"], // Specify font weights (optional), // Adjust if necessary
  variable: "--font-jetbrains_mono",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={jetBrainsMono.variable}>
        <Header />
        <StairTranstion />
        <PageTranstation>{children}</PageTranstation>
      </body>
    </html>
  );
}
